import { useState } from 'react'
import { paymentReviewStore } from '../payments/paymentReviewStore'

export function BookingTracker() {
  const [open, setOpen] = useState(false)
  const [reference, setReference] = useState('')
  const [result, setResult] = useState<ReturnType<typeof paymentReviewStore.list>[number] | null | undefined>(undefined)
  const find = () => setResult(paymentReviewStore.list().find(item => item.reference?.toLowerCase() === reference.trim().toLowerCase()) ?? null)
  return <><button type="button" onClick={() => setOpen(true)} className="fixed right-4 top-4 z-[110] rounded-xl border border-white/10 bg-zinc-950/80 px-3 py-2 text-xs text-zinc-200 shadow-xl backdrop-blur">Track booking</button>{open && <div className="fixed inset-0 z-[140] grid place-items-center bg-zinc-950/80 p-4 backdrop-blur"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-[#111113] p-6 text-white"><div className="flex justify-between"><div><p className="font-mono text-[10px] uppercase tracking-widest text-emerald-400">Booking tracker</p><h2 className="font-serif text-xl font-bold">Track your booking</h2></div><button type="button" onClick={() => setOpen(false)} className="text-zinc-400">×</button></div><div className="mt-5 flex gap-2"><input value={reference} onChange={event => setReference(event.target.value)} onKeyDown={event => event.key === 'Enter' && find()} placeholder="ABX-2026-8F4K92" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-white/5 px-3 py-2.5 text-sm text-white outline-none"/><button type="button" onClick={find} className="rounded-xl bg-emerald-400 px-4 text-xs font-bold text-zinc-950">Track</button></div>{result === null && <p className="mt-4 text-xs text-amber-200">We couldn’t find that booking reference on this device.</p>}{result && <div className="mt-5 rounded-2xl border border-white/10 bg-white/[.03] p-4 text-sm"><p className="font-semibold">{result.eventName}</p><p className="mt-2 text-zinc-400">{result.packageName} · Seat {result.seatLabel}</p><p className="mt-3 inline-flex rounded-full bg-emerald-400/10 px-2 py-1 text-xs capitalize text-emerald-300">{result.status.replaceAll('_', ' ')}</p></div>}</div></div>}</>
}
