import type { LangCode } from './localeConfig'

export type UiTranslationKey = keyof typeof uiTranslations.en
type Dictionary = Record<string, string>

const en = {
  'navigation.home':'Home','navigation.about':'About','navigation.venue':'Venue','navigation.packages':'Packages','navigation.timeline':'Timeline','navigation.reviews':'Reviews','navigation.faq':'FAQ','navigation.contact':'Contact','navigation.bookTickets':'Book Tickets','navigation.reserve':'Reserve','navigation.openMenu':'Open menu','navigation.closeMenu':'Close menu','navigation.lightMode':'Switch to light mode','navigation.darkMode':'Switch to dark mode','navigation.language':'Language',
  'hero.liveEvent':'Live event','hero.featuredMoment':'Featured moment','hero.highlight':'Event highlight {number}','hero.dateTime':'Date & time','hero.venue':'Venue','hero.featuring':'Featuring {guests}.','hero.description':'An unforgettable live experience, presented by Apex Bookings.','hero.bookTickets':'Book tickets','hero.explore':'Explore event','hero.highlights':'Event highlights','hero.showCard':'Show {label}','hero.previous':'Previous event image','hero.next':'Next event image','hero.viewPackages':'View packages','hero.from':'From {price}','hero.seatsAvailable':'{count} seats available','hero.packagesAvailable':'{count} packages','hero.doors':'Doors {time}','hero.slide':'Slide {current} of {total}',
  'about.section':'About the Show','about.mediaEmpty':'Add an event image or video in Event Studio.','about.eventVideo':'Event video','about.eventImage':'Event image','about.showDate':'Show Date','about.official':'Official event','about.everyTicket':'Every Ticket Includes',
  'venue.section':'Venue','venue.facts':'Venue Facts','venue.openMaps':'Open in Maps','venue.directions':'Get Directions',
  'timeline.eyebrow':'The Evening','timeline.heading':'Show Schedule',
  'reviews.eyebrow':'From Our Attendees','reviews.heading':'What People Are Saying',
  'faq.eyebrow':'Questions','faq.heading':'Frequently Asked','faq.expand':'Expand answer','faq.collapse':'Collapse answer',
  'footer.event':'Event','footer.support':'Support','footer.legal':'Legal','footer.about':'About','footer.schedule':'Schedule','footer.venue':'Venue Info','footer.packages':'Packages','footer.help':'Help Center','footer.contact':'Contact Us','footer.refunds':'Refund Policy','footer.liveChat':'Live Chat','footer.privacy':'Privacy Policy','footer.terms':'Terms of Service','footer.cookies':'Cookie Policy','footer.accessibility':'Accessibility','footer.opening':'Opening {label}…',
  'booking.selectPackage':'Select Package','booking.selectSeat':'Select Seat','booking.quantity':'Quantity','booking.continue':'Continue','booking.back':'Back','booking.customerDetails':'Customer Details','booking.fullName':'Full Name','booking.email':'Email','booking.phone':'Phone','booking.country':'Country','booking.paymentMethod':'Payment Method','booking.summary':'Booking Summary','booking.subtotal':'Subtotal','booking.total':'Total','booking.confirm':'Confirm Booking','booking.required':'This field is required','booking.loading':'Loading booking…','booking.empty':'No booking options are available.','booking.error':'The booking could not be completed.','booking.reference':'Booking reference','booking.sessionExpired':'Booking session expired','booking.sessionExpiredBody':'Your temporary checkout session was inactive for more than 10 minutes. Completed bookings and submitted payments remain safe.','booking.recover':'Recover submitted booking','booking.restart':'Restart booking safely','booking.restored':'Your booking progress has been restored.',
  'payment.instructions':'Payment Instructions','payment.awaitingBank':'Awaiting bank details','payment.awaitingPayment':'Awaiting payment','payment.uploadProof':'Upload payment proof','payment.submitted':'Payment submitted','payment.pending':'Pending approval','payment.approved':'Payment approved','payment.declined':'Payment declined','payment.declineReason':'Decline reason','payment.expired':'Payment expired','payment.retry':'Retry payment','payment.downloadTicket':'Download ticket','payment.returnEvent':'Return to event','payment.reference':'Payment reference','payment.requestBank':'Request Bank Details','payment.chooseAnother':'Choose Another Payment Method','payment.confirmBank':'Request Bank Transfer Details?','payment.bankBody':'A temporary bank account will be generated for this booking and will remain valid for 30 minutes.','payment.bankAvailable':'Bank Details Available','payment.copyAll':'Copy All Details','payment.doNotClose':'Do not close this page.','payment.windowExpired':'Transfer window expired',
  'ticket.details':'Ticket details','ticket.eventDate':'Event date','ticket.venue':'Venue','ticket.package':'Package','ticket.seat':'Seat','ticket.attendee':'Attendee','ticket.status':'Ticket status','ticket.valid':'Valid ticket','ticket.invalid':'Invalid ticket','ticket.validated':'Already validated','ticket.cancelled':'Cancelled ticket','ticket.download':'Download ticket','ticket.verified':'Verified digital pass',
  'chat.title':'Apex Support','chat.online':'Online · typically replies in minutes','chat.close':'Close','chat.welcome':'Welcome to Support','chat.emailPrompt':'Enter your email to continue an existing conversation or start a new one.','chat.email':'Email address','chat.continue':'Continue','chat.placeholder':'Type a message…','chat.send':'Send','chat.open':'Open support chat','chat.greeting':'Hi! How can we help with your booking today?','chat.helpContext':'What would you like help with regarding {context}?',
  'common.cancel':'Cancel','common.close':'Close','common.copy':'Copy','common.loading':'Loading…','common.retry':'Retry','common.notRequired':'Not required','common.error':'Something went wrong','common.previous':'Previous','common.next':'Next','common.confirm':'Confirm',
  'status.restored':'Welcome back — your previous work has been restored.','status.offline':'Offline — progress is kept on this device','status.notFound':'Page not found',
} as const

const fr: Dictionary = {
  'navigation.home':'Accueil','navigation.about':'À propos','navigation.venue':'Lieu','navigation.packages':'Forfaits','navigation.timeline':'Programme','navigation.reviews':'Avis','navigation.faq':'FAQ','navigation.contact':'Contact','navigation.bookTickets':'Réserver','navigation.reserve':'Réserver','navigation.openMenu':'Ouvrir le menu','navigation.closeMenu':'Fermer le menu','navigation.lightMode':'Passer au mode clair','navigation.darkMode':'Passer au mode sombre','navigation.language':'Langue',
  'hero.liveEvent':'Événement en direct','hero.featuredMoment':'Moment vedette','hero.highlight':'Temps fort {number}','hero.dateTime':'Date et heure','hero.venue':'Lieu','hero.featuring':'Avec {guests}.','hero.description':'Une expérience live inoubliable, présentée par Apex Bookings.','hero.bookTickets':'Réserver','hero.explore':'Découvrir','hero.highlights':'Temps forts','hero.showCard':'Afficher {label}','hero.previous':'Image précédente','hero.next':'Image suivante','hero.viewPackages':'Voir les forfaits','hero.from':'À partir de {price}','hero.seatsAvailable':'{count} places disponibles','hero.packagesAvailable':'{count} forfaits','hero.doors':'Ouverture {time}','hero.slide':'Diapositive {current} sur {total}',
  'about.section':'À propos du spectacle','about.mediaEmpty':'Ajoutez une image ou une vidéo dans Event Studio.','about.eventVideo':'Vidéo de l’événement','about.eventImage':'Image de l’événement','about.showDate':'Date du spectacle','about.official':'Événement officiel','about.everyTicket':'Chaque billet comprend',
  'venue.section':'Lieu','venue.facts':'Informations sur le lieu','venue.openMaps':'Ouvrir dans Maps','venue.directions':'Itinéraire','timeline.eyebrow':'La soirée','timeline.heading':'Programme','reviews.eyebrow':'Avis des participants','reviews.heading':'Ce qu’ils en pensent','faq.eyebrow':'Questions','faq.heading':'Questions fréquentes',
  'footer.event':'Événement','footer.support':'Assistance','footer.legal':'Mentions légales','footer.about':'À propos','footer.schedule':'Programme','footer.venue':'Informations du lieu','footer.packages':'Forfaits','footer.help':'Centre d’aide','footer.contact':'Nous contacter','footer.refunds':'Politique de remboursement','footer.liveChat':'Chat en direct','footer.privacy':'Confidentialité','footer.terms':'Conditions d’utilisation','footer.cookies':'Politique des cookies','footer.accessibility':'Accessibilité','footer.opening':'Ouverture de {label}…',
  'booking.selectPackage':'Choisir un forfait','booking.selectSeat':'Choisir une place','booking.quantity':'Quantité','booking.continue':'Continuer','booking.back':'Retour','booking.customerDetails':'Informations client','booking.fullName':'Nom complet','booking.email':'E-mail','booking.phone':'Téléphone','booking.country':'Pays','booking.paymentMethod':'Mode de paiement','booking.summary':'Récapitulatif','booking.subtotal':'Sous-total','booking.total':'Total','booking.confirm':'Confirmer la réservation','booking.required':'Ce champ est obligatoire','booking.loading':'Chargement de la réservation…','booking.empty':'Aucune option de réservation disponible.','booking.error':'La réservation n’a pas pu être effectuée.','booking.reference':'Référence de réservation','booking.sessionExpired':'Session de réservation expirée','booking.sessionExpiredBody':'Votre session a été inactive plus de 10 minutes. Les réservations terminées et paiements soumis restent sécurisés.','booking.recover':'Récupérer la réservation soumise','booking.restart':'Recommencer en toute sécurité','booking.restored':'Votre progression a été restaurée.',
  'payment.instructions':'Instructions de paiement','payment.awaitingBank':'En attente des coordonnées bancaires','payment.awaitingPayment':'En attente du paiement','payment.uploadProof':'Télécharger la preuve','payment.submitted':'Paiement soumis','payment.pending':'En attente d’approbation','payment.approved':'Paiement approuvé','payment.declined':'Paiement refusé','payment.declineReason':'Motif du refus','payment.expired':'Paiement expiré','payment.retry':'Réessayer','payment.downloadTicket':'Télécharger le billet','payment.returnEvent':'Retour à l’événement','payment.reference':'Référence de paiement','payment.requestBank':'Demander les coordonnées bancaires','payment.chooseAnother':'Choisir un autre mode','payment.confirmBank':'Demander les coordonnées bancaires ?','payment.bankBody':'Un compte bancaire temporaire sera généré pour cette réservation et restera valable 30 minutes.','payment.bankAvailable':'Coordonnées bancaires disponibles','payment.copyAll':'Tout copier','payment.doNotClose':'Ne fermez pas cette page.','payment.windowExpired':'Délai de transfert expiré',
  'ticket.details':'Détails du billet','ticket.eventDate':'Date','ticket.venue':'Lieu','ticket.package':'Forfait','ticket.seat':'Place','ticket.attendee':'Participant','ticket.status':'Statut du billet','ticket.valid':'Billet valide','ticket.invalid':'Billet invalide','ticket.validated':'Déjà validé','ticket.cancelled':'Billet annulé','ticket.download':'Télécharger le billet','ticket.verified':'Pass numérique vérifié',
  'chat.title':'Assistance Apex','chat.online':'En ligne · répond généralement en quelques minutes','chat.close':'Fermer','chat.welcome':'Bienvenue dans l’assistance','chat.emailPrompt':'Saisissez votre e-mail pour continuer ou démarrer une conversation.','chat.email':'Adresse e-mail','chat.continue':'Continuer','chat.placeholder':'Écrivez un message…','chat.send':'Envoyer','chat.open':'Ouvrir le chat','chat.greeting':'Bonjour ! Comment pouvons-nous vous aider ?','common.cancel':'Annuler','common.close':'Fermer','common.copy':'Copier','common.loading':'Chargement…','common.retry':'Réessayer','common.notRequired':'Non requis','common.error':'Une erreur est survenue','common.previous':'Précédent','common.next':'Suivant','common.confirm':'Confirmer','status.notFound':'Page introuvable'
}

const de: Dictionary = {'navigation.home':'Start','navigation.about':'Über','navigation.venue':'Veranstaltungsort','navigation.packages':'Pakete','navigation.timeline':'Ablauf','navigation.reviews':'Bewertungen','navigation.contact':'Kontakt','navigation.bookTickets':'Tickets buchen','navigation.openMenu':'Menü öffnen','navigation.closeMenu':'Menü schließen','hero.liveEvent':'Live-Event','hero.dateTime':'Datum und Uhrzeit','hero.venue':'Veranstaltungsort','hero.bookTickets':'Tickets buchen','hero.explore':'Event entdecken','hero.previous':'Vorheriges Bild','hero.next':'Nächstes Bild','hero.viewPackages':'Pakete ansehen','about.section':'Über die Show','about.showDate':'Showdatum','about.official':'Offizielles Event','about.everyTicket':'Jedes Ticket enthält','venue.openMaps':'In Maps öffnen','venue.facts':'Informationen zum Ort','timeline.heading':'Zeitplan','reviews.eyebrow':'Von unseren Gästen','reviews.heading':'Das sagen unsere Gäste','faq.eyebrow':'Fragen','faq.heading':'Häufig gestellte Fragen','footer.event':'Event','footer.support':'Support','footer.legal':'Rechtliches','footer.contact':'Kontakt','booking.selectPackage':'Paket auswählen','booking.selectSeat':'Sitz auswählen','booking.quantity':'Anzahl','booking.continue':'Weiter','booking.back':'Zurück','booking.customerDetails':'Kundendaten','booking.fullName':'Vollständiger Name','booking.email':'E-Mail','booking.phone':'Telefon','booking.country':'Land','booking.paymentMethod':'Zahlungsmethode','booking.summary':'Buchungsübersicht','booking.subtotal':'Zwischensumme','booking.total':'Gesamt','booking.confirm':'Buchung bestätigen','booking.reference':'Buchungsreferenz','booking.sessionExpired':'Buchungssitzung abgelaufen','booking.recover':'Gesendete Buchung wiederherstellen','booking.restart':'Buchung sicher neu starten','payment.pending':'Genehmigung ausstehend','payment.approved':'Zahlung genehmigt','payment.declined':'Zahlung abgelehnt','payment.uploadProof':'Zahlungsnachweis hochladen','payment.downloadTicket':'Ticket herunterladen','ticket.details':'Ticketdetails','ticket.valid':'Gültiges Ticket','ticket.invalid':'Ungültiges Ticket','ticket.validated':'Bereits validiert','ticket.cancelled':'Storniertes Ticket','chat.title':'Apex Support','chat.close':'Schließen','chat.welcome':'Willkommen beim Support','chat.email':'E-Mail-Adresse','chat.continue':'Weiter','chat.placeholder':'Nachricht eingeben…','chat.send':'Senden','common.cancel':'Abbrechen','common.close':'Schließen','common.copy':'Kopieren','common.loading':'Wird geladen…','common.retry':'Erneut versuchen','common.error':'Etwas ist schiefgelaufen'}
const es: Dictionary = {'navigation.home':'Inicio','navigation.about':'Acerca de','navigation.venue':'Lugar','navigation.packages':'Paquetes','navigation.timeline':'Programa','navigation.reviews':'Reseñas','navigation.contact':'Contacto','navigation.bookTickets':'Reservar entradas','navigation.openMenu':'Abrir menú','navigation.closeMenu':'Cerrar menú','hero.liveEvent':'Evento en vivo','hero.dateTime':'Fecha y hora','hero.venue':'Lugar','hero.bookTickets':'Reservar entradas','hero.explore':'Explorar evento','hero.previous':'Imagen anterior','hero.next':'Imagen siguiente','hero.viewPackages':'Ver paquetes','about.section':'Sobre el espectáculo','about.showDate':'Fecha','about.official':'Evento oficial','about.everyTicket':'Cada entrada incluye','venue.openMaps':'Abrir en Maps','venue.facts':'Datos del lugar','timeline.heading':'Programa del evento','reviews.eyebrow':'Nuestros asistentes','reviews.heading':'Lo que dice la gente','faq.eyebrow':'Preguntas','faq.heading':'Preguntas frecuentes','footer.event':'Evento','footer.support':'Soporte','footer.legal':'Legal','footer.contact':'Contacto','booking.selectPackage':'Seleccionar paquete','booking.selectSeat':'Seleccionar asiento','booking.quantity':'Cantidad','booking.continue':'Continuar','booking.back':'Atrás','booking.customerDetails':'Datos del cliente','booking.fullName':'Nombre completo','booking.email':'Correo electrónico','booking.phone':'Teléfono','booking.country':'País','booking.paymentMethod':'Método de pago','booking.summary':'Resumen de reserva','booking.subtotal':'Subtotal','booking.total':'Total','booking.confirm':'Confirmar reserva','booking.reference':'Referencia de reserva','booking.sessionExpired':'La sesión de reserva caducó','booking.recover':'Recuperar reserva enviada','booking.restart':'Reiniciar reserva de forma segura','payment.pending':'Pendiente de aprobación','payment.approved':'Pago aprobado','payment.declined':'Pago rechazado','payment.uploadProof':'Subir comprobante','payment.downloadTicket':'Descargar entrada','ticket.details':'Detalles de la entrada','ticket.valid':'Entrada válida','ticket.invalid':'Entrada no válida','ticket.validated':'Ya validada','ticket.cancelled':'Entrada cancelada','chat.title':'Soporte Apex','chat.close':'Cerrar','chat.welcome':'Bienvenido al soporte','chat.email':'Correo electrónico','chat.continue':'Continuar','chat.placeholder':'Escribe un mensaje…','chat.send':'Enviar','common.cancel':'Cancelar','common.close':'Cerrar','common.copy':'Copiar','common.loading':'Cargando…','common.retry':'Reintentar','common.error':'Algo salió mal'}
const pt: Dictionary = {'navigation.home':'Início','navigation.about':'Sobre','navigation.venue':'Local','navigation.packages':'Pacotes','navigation.timeline':'Programação','navigation.reviews':'Avaliações','navigation.contact':'Contato','navigation.bookTickets':'Comprar ingressos','navigation.openMenu':'Abrir menu','navigation.closeMenu':'Fechar menu','hero.liveEvent':'Evento ao vivo','hero.dateTime':'Data e hora','hero.venue':'Local','hero.bookTickets':'Comprar ingressos','hero.explore':'Explorar evento','hero.previous':'Imagem anterior','hero.next':'Próxima imagem','hero.viewPackages':'Ver pacotes','about.section':'Sobre o show','about.showDate':'Data do show','about.official':'Evento oficial','about.everyTicket':'Todo ingresso inclui','venue.openMaps':'Abrir no Maps','venue.facts':'Informações do local','timeline.heading':'Programação do evento','reviews.eyebrow':'Nossos participantes','reviews.heading':'O que as pessoas dizem','faq.eyebrow':'Perguntas','faq.heading':'Perguntas frequentes','footer.event':'Evento','footer.support':'Suporte','footer.legal':'Legal','footer.contact':'Contato','booking.selectPackage':'Selecionar pacote','booking.selectSeat':'Selecionar assento','booking.quantity':'Quantidade','booking.continue':'Continuar','booking.back':'Voltar','booking.customerDetails':'Dados do cliente','booking.fullName':'Nome completo','booking.email':'E-mail','booking.phone':'Telefone','booking.country':'País','booking.paymentMethod':'Forma de pagamento','booking.summary':'Resumo da reserva','booking.subtotal':'Subtotal','booking.total':'Total','booking.confirm':'Confirmar reserva','booking.reference':'Referência da reserva','booking.sessionExpired':'Sessão de reserva expirada','booking.recover':'Recuperar reserva enviada','booking.restart':'Reiniciar reserva com segurança','payment.pending':'Aguardando aprovação','payment.approved':'Pagamento aprovado','payment.declined':'Pagamento recusado','payment.uploadProof':'Enviar comprovante','payment.downloadTicket':'Baixar ingresso','ticket.details':'Detalhes do ingresso','ticket.valid':'Ingresso válido','ticket.invalid':'Ingresso inválido','ticket.validated':'Já validado','ticket.cancelled':'Ingresso cancelado','chat.title':'Suporte Apex','chat.close':'Fechar','chat.welcome':'Bem-vindo ao suporte','chat.email':'Endereço de e-mail','chat.continue':'Continuar','chat.placeholder':'Digite uma mensagem…','chat.send':'Enviar','common.cancel':'Cancelar','common.close':'Fechar','common.copy':'Copiar','common.loading':'Carregando…','common.retry':'Tentar novamente','common.error':'Algo deu errado'}
const it: Dictionary = {'navigation.home':'Home','navigation.about':'Chi siamo','navigation.venue':'Luogo','navigation.packages':'Pacchetti','navigation.timeline':'Programma','navigation.reviews':'Recensioni','navigation.contact':'Contatti','navigation.bookTickets':'Acquista biglietti','navigation.openMenu':'Apri menu','navigation.closeMenu':'Chiudi menu','hero.liveEvent':'Evento dal vivo','hero.dateTime':'Data e ora','hero.venue':'Luogo','hero.bookTickets':'Acquista biglietti','hero.explore':'Scopri evento','hero.previous':'Immagine precedente','hero.next':'Immagine successiva','hero.viewPackages':'Vedi pacchetti','about.section':'Sullo spettacolo','about.showDate':'Data spettacolo','about.official':'Evento ufficiale','about.everyTicket':'Ogni biglietto include','venue.openMaps':'Apri in Maps','venue.facts':'Informazioni sul luogo','timeline.heading':'Programma evento','reviews.eyebrow':'I nostri partecipanti','reviews.heading':'Cosa dicono le persone','faq.eyebrow':'Domande','faq.heading':'Domande frequenti','footer.event':'Evento','footer.support':'Supporto','footer.legal':'Note legali','footer.contact':'Contatti','booking.selectPackage':'Seleziona pacchetto','booking.selectSeat':'Seleziona posto','booking.quantity':'Quantità','booking.continue':'Continua','booking.back':'Indietro','booking.customerDetails':'Dati cliente','booking.fullName':'Nome completo','booking.email':'Email','booking.phone':'Telefono','booking.country':'Paese','booking.paymentMethod':'Metodo di pagamento','booking.summary':'Riepilogo prenotazione','booking.subtotal':'Subtotale','booking.total':'Totale','booking.confirm':'Conferma prenotazione','booking.reference':'Riferimento prenotazione','booking.sessionExpired':'Sessione di prenotazione scaduta','booking.recover':'Recupera prenotazione inviata','booking.restart':'Riavvia prenotazione in sicurezza','payment.pending':'In attesa di approvazione','payment.approved':'Pagamento approvato','payment.declined':'Pagamento rifiutato','payment.uploadProof':'Carica prova di pagamento','payment.downloadTicket':'Scarica biglietto','ticket.details':'Dettagli biglietto','ticket.valid':'Biglietto valido','ticket.invalid':'Biglietto non valido','ticket.validated':'Già convalidato','ticket.cancelled':'Biglietto annullato','chat.title':'Supporto Apex','chat.close':'Chiudi','chat.welcome':'Benvenuto nel supporto','chat.email':'Indirizzo email','chat.continue':'Continua','chat.placeholder':'Scrivi un messaggio…','chat.send':'Invia','common.cancel':'Annulla','common.close':'Chiudi','common.copy':'Copia','common.loading':'Caricamento…','common.retry':'Riprova','common.error':'Qualcosa è andato storto'}

Object.assign(en, {'ticket.verifying':'Verifying ticket…','ticket.invalidDescription':'We could not verify this ticket. It may be fake, refunded, cancelled, or not yet approved.','ticket.scannedData':'Scanned data','ticket.returnHome':'Return home','ticket.verification':'Apex Verification','ticket.secureScan':'Secure scan','ticket.verifiedAttendee':'Verified attendee','ticket.officialRecord':'Official ticket record','ticket.admitOne':'Admit one','ticket.time':'Time','ticket.bookingRef':'Booking reference','ticket.number':'Ticket number','ticket.approved':'Approved','ticket.scannedAt':'Scanned at {time}','ticket.unknown':'Unknown','ticket.presents':'{host} presents'})
Object.assign(fr, {'ticket.verifying':'Vérification du billet…','ticket.invalidDescription':'Nous ne pouvons pas vérifier ce billet. Il peut être faux, remboursé, annulé ou pas encore approuvé.','ticket.scannedData':'Données scannées','ticket.returnHome':'Retour à l’accueil','ticket.verification':'Vérification Apex','ticket.secureScan':'Scan sécurisé','ticket.verifiedAttendee':'Participant vérifié','ticket.officialRecord':'Billet officiel','ticket.admitOne':'Valable pour une personne','ticket.time':'Heure','ticket.bookingRef':'Référence de réservation','ticket.number':'Numéro du billet','ticket.approved':'Approuvé','ticket.scannedAt':'Scanné à {time}','ticket.unknown':'Inconnu','ticket.presents':'Présenté par {host}'})
Object.assign(de, {'ticket.verifying':'Ticket wird geprüft…','ticket.invalidDescription':'Dieses Ticket konnte nicht bestätigt werden. Es kann gefälscht, erstattet, storniert oder noch nicht genehmigt sein.','ticket.scannedData':'Gescannte Daten','ticket.returnHome':'Zur Startseite','ticket.verification':'Apex-Verifizierung','ticket.secureScan':'Sicherer Scan','ticket.verifiedAttendee':'Verifizierter Gast','ticket.officialRecord':'Offizieller Ticketnachweis','ticket.admitOne':'Einlass für eine Person','ticket.time':'Uhrzeit','ticket.bookingRef':'Buchungsreferenz','ticket.number':'Ticketnummer','ticket.approved':'Genehmigt','ticket.scannedAt':'Gescannt um {time}','ticket.unknown':'Unbekannt','ticket.presents':'{host} präsentiert'})
Object.assign(es, {'ticket.verifying':'Verificando entrada…','ticket.invalidDescription':'No pudimos verificar esta entrada. Puede ser falsa, reembolsada, cancelada o aún no aprobada.','ticket.scannedData':'Datos escaneados','ticket.returnHome':'Volver al inicio','ticket.verification':'Verificación Apex','ticket.secureScan':'Escaneo seguro','ticket.verifiedAttendee':'Asistente verificado','ticket.officialRecord':'Registro oficial de entrada','ticket.admitOne':'Admite a una persona','ticket.time':'Hora','ticket.bookingRef':'Referencia de reserva','ticket.number':'Número de entrada','ticket.approved':'Aprobado','ticket.scannedAt':'Escaneado a las {time}','ticket.unknown':'Desconocido','ticket.presents':'Presentado por {host}'})
Object.assign(pt, {'ticket.verifying':'Verificando ingresso…','ticket.invalidDescription':'Não foi possível verificar este ingresso. Ele pode ser falso, reembolsado, cancelado ou ainda não aprovado.','ticket.scannedData':'Dados escaneados','ticket.returnHome':'Voltar ao início','ticket.verification':'Verificação Apex','ticket.secureScan':'Leitura segura','ticket.verifiedAttendee':'Participante verificado','ticket.officialRecord':'Registro oficial do ingresso','ticket.admitOne':'Válido para uma pessoa','ticket.time':'Hora','ticket.bookingRef':'Referência da reserva','ticket.number':'Número do ingresso','ticket.approved':'Aprovado','ticket.scannedAt':'Escaneado às {time}','ticket.unknown':'Desconhecido','ticket.presents':'Apresentado por {host}'})
Object.assign(it, {'ticket.verifying':'Verifica del biglietto…','ticket.invalidDescription':'Non è stato possibile verificare questo biglietto. Potrebbe essere falso, rimborsato, annullato o non ancora approvato.','ticket.scannedData':'Dati scansionati','ticket.returnHome':'Torna alla home','ticket.verification':'Verifica Apex','ticket.secureScan':'Scansione sicura','ticket.verifiedAttendee':'Partecipante verificato','ticket.officialRecord':'Registro ufficiale del biglietto','ticket.admitOne':'Ingresso per una persona','ticket.time':'Ora','ticket.bookingRef':'Riferimento prenotazione','ticket.number':'Numero biglietto','ticket.approved':'Approvato','ticket.scannedAt':'Scansionato alle {time}','ticket.unknown':'Sconosciuto','ticket.presents':'Presentato da {host}'})

Object.assign(en, {'booking.selectSeatHeading':'Select your seat — {package} · {count} seats available','booking.alreadyTaken':'Already taken','booking.seatSelected':'Seat {seat} selected','booking.oneSeat':'You can book one seat per transaction. To reserve another seat, start a new booking after completion.','booking.ticketEmail':'Your ticket and QR code will be sent to the email address above after payment confirmation.','booking.currentStatus':'Current status','booking.waitingBank':'Waiting for bank details','booking.eventName':'Event name','booking.selectedPackage':'Selected package','booking.selectedSeat':'Selected seat','booking.totalAmount':'Total amount','booking.customerEmail':'Customer email'})
Object.assign(fr, {'booking.selectSeatHeading':'Choisissez votre place — {package} · {count} places disponibles','booking.alreadyTaken':'Déjà prise','booking.seatSelected':'Place {seat} sélectionnée','booking.oneSeat':'Vous pouvez réserver une place par transaction. Pour une autre place, démarrez une nouvelle réservation après avoir terminé.','booking.ticketEmail':'Votre billet et votre QR code seront envoyés à l’adresse e-mail ci-dessus après confirmation du paiement.','booking.currentStatus':'Statut actuel','booking.waitingBank':'En attente des coordonnées bancaires','booking.eventName':'Nom de l’événement','booking.selectedPackage':'Forfait sélectionné','booking.selectedSeat':'Place sélectionnée','booking.totalAmount':'Montant total','booking.customerEmail':'E-mail du client'})
Object.assign(de, {'booking.selectSeatHeading':'Sitzplatz auswählen — {package} · {count} Plätze verfügbar','booking.alreadyTaken':'Bereits belegt','booking.seatSelected':'Sitz {seat} ausgewählt','booking.oneSeat':'Pro Vorgang kann ein Sitzplatz gebucht werden. Buchen Sie nach Abschluss erneut, um einen weiteren zu reservieren.','booking.ticketEmail':'Ticket und QR-Code werden nach Zahlungsbestätigung an die obige E-Mail-Adresse gesendet.','booking.currentStatus':'Aktueller Status','booking.waitingBank':'Warten auf Bankdaten','booking.eventName':'Eventname','booking.selectedPackage':'Ausgewähltes Paket','booking.selectedSeat':'Ausgewählter Sitz','booking.totalAmount':'Gesamtbetrag','booking.customerEmail':'Kunden-E-Mail'})
Object.assign(es, {'booking.selectSeatHeading':'Selecciona tu asiento — {package} · {count} asientos disponibles','booking.alreadyTaken':'Ya está ocupado','booking.seatSelected':'Asiento {seat} seleccionado','booking.oneSeat':'Puedes reservar un asiento por transacción. Para reservar otro, inicia una nueva reserva al terminar.','booking.ticketEmail':'La entrada y el código QR se enviarán al correo anterior tras confirmar el pago.','booking.currentStatus':'Estado actual','booking.waitingBank':'Esperando datos bancarios','booking.eventName':'Nombre del evento','booking.selectedPackage':'Paquete seleccionado','booking.selectedSeat':'Asiento seleccionado','booking.totalAmount':'Importe total','booking.customerEmail':'Correo del cliente'})
Object.assign(pt, {'booking.selectSeatHeading':'Selecione seu assento — {package} · {count} assentos disponíveis','booking.alreadyTaken':'Já ocupado','booking.seatSelected':'Assento {seat} selecionado','booking.oneSeat':'Você pode reservar um assento por transação. Para outro assento, inicie uma nova reserva após concluir.','booking.ticketEmail':'O ingresso e o QR code serão enviados ao e-mail acima após a confirmação do pagamento.','booking.currentStatus':'Status atual','booking.waitingBank':'Aguardando dados bancários','booking.eventName':'Nome do evento','booking.selectedPackage':'Pacote selecionado','booking.selectedSeat':'Assento selecionado','booking.totalAmount':'Valor total','booking.customerEmail':'E-mail do cliente'})
Object.assign(it, {'booking.selectSeatHeading':'Seleziona il posto — {package} · {count} posti disponibili','booking.alreadyTaken':'Già occupato','booking.seatSelected':'Posto {seat} selezionato','booking.oneSeat':'Puoi prenotare un posto per transazione. Per un altro posto, avvia una nuova prenotazione dopo il completamento.','booking.ticketEmail':'Il biglietto e il codice QR verranno inviati all’indirizzo email sopra dopo la conferma del pagamento.','booking.currentStatus':'Stato attuale','booking.waitingBank':'In attesa dei dati bancari','booking.eventName':'Nome evento','booking.selectedPackage':'Pacchetto selezionato','booking.selectedSeat':'Posto selezionato','booking.totalAmount':'Importo totale','booking.customerEmail':'Email cliente'})

Object.assign(en, {'common.copied':'Copied'}); Object.assign(fr, {'common.copied':'Copié'}); Object.assign(de, {'common.copied':'Kopiert'}); Object.assign(es, {'common.copied':'Copiado'}); Object.assign(pt, {'common.copied':'Copiado'}); Object.assign(it, {'common.copied':'Copiato'})

Object.assign(de, {
  'navigation.faq':'FAQ','navigation.reserve':'Reservieren','navigation.lightMode':'Hellen Modus aktivieren','navigation.darkMode':'Dunklen Modus aktivieren','navigation.language':'Sprache',
  'hero.featuredMoment':'Besonderer Moment','hero.highlight':'Highlight {number}','hero.featuring':'Mit {guests}.','hero.description':'Ein unvergessliches Live-Erlebnis, präsentiert von Apex Bookings.','hero.highlights':'Highlights','hero.showCard':'{label} anzeigen','hero.from':'Ab {price}','hero.seatsAvailable':'{count} Plätze verfügbar','hero.packagesAvailable':'{count} Pakete','hero.doors':'Einlass {time}','hero.slide':'Folie {current} von {total}',
  'about.mediaEmpty':'Fügen Sie in Event Studio ein Bild oder Video hinzu.','about.eventVideo':'Eventvideo','about.eventImage':'Eventbild','venue.section':'Veranstaltungsort','venue.directions':'Wegbeschreibung','timeline.eyebrow':'Der Abend','reviews.heading':'Das sagen unsere Gäste','footer.about':'Über das Event','footer.schedule':'Ablauf','footer.venue':'Veranstaltungsort','footer.packages':'Pakete','footer.help':'Hilfe-Center','footer.refunds':'Rückerstattungen','footer.liveChat':'Live-Chat','footer.privacy':'Datenschutz','footer.terms':'Nutzungsbedingungen','footer.cookies':'Cookie-Richtlinie','footer.accessibility':'Barrierefreiheit','footer.opening':'{label} wird geöffnet…',
  'booking.required':'Dieses Feld ist erforderlich','booking.loading':'Buchung wird geladen…','booking.empty':'Keine Buchungsoption verfügbar.','booking.error':'Die Buchung konnte nicht abgeschlossen werden.','booking.sessionExpiredBody':'Ihre Sitzung war länger als 10 Minuten inaktiv. Abgeschlossene Buchungen und eingereichte Zahlungen bleiben sicher.','booking.restored':'Ihr Buchungsfortschritt wurde wiederhergestellt.','payment.instructions':'Zahlungsanweisungen','payment.awaitingBank':'Warten auf Bankdaten','payment.awaitingPayment':'Warten auf Zahlung','payment.submitted':'Zahlung eingereicht','payment.declineReason':'Ablehnungsgrund','payment.expired':'Zahlung abgelaufen','payment.retry':'Zahlung erneut versuchen','payment.returnEvent':'Zurück zum Event','payment.reference':'Zahlungsreferenz','payment.requestBank':'Bankdaten anfordern','payment.chooseAnother':'Andere Zahlungsmethode wählen','payment.confirmBank':'Banküberweisungsdaten anfordern?','payment.bankBody':'Für diese Buchung wird ein temporäres Bankkonto erstellt, das 30 Minuten gültig bleibt.','payment.bankAvailable':'Bankdaten verfügbar','payment.copyAll':'Alle Daten kopieren','payment.doNotClose':'Schließen Sie diese Seite nicht.','payment.windowExpired':'Überweisungsfenster abgelaufen',
  'ticket.eventDate':'Eventdatum','ticket.venue':'Veranstaltungsort','ticket.package':'Paket','ticket.seat':'Sitz','ticket.attendee':'Teilnehmer','ticket.status':'Ticketstatus','ticket.download':'Ticket herunterladen','ticket.verified':'Verifizierter digitaler Pass','chat.online':'Online · antwortet meist in wenigen Minuten','chat.emailPrompt':'Geben Sie Ihre E-Mail-Adresse ein, um eine Unterhaltung fortzusetzen oder zu beginnen.','chat.open':'Support-Chat öffnen','chat.greeting':'Hallo! Wie können wir bei Ihrer Buchung helfen?','chat.helpContext':'Wobei benötigen Sie Hilfe zu {context}?','common.previous':'Zurück','common.next':'Weiter','common.confirm':'Bestätigen','common.notRequired':'Nicht erforderlich','status.restored':'Willkommen zurück — Ihre vorherige Arbeit wurde wiederhergestellt.','status.offline':'Offline — der Fortschritt bleibt auf diesem Gerät','status.notFound':'Seite nicht gefunden'
})
Object.assign(es, {
  'navigation.faq':'Preguntas frecuentes','navigation.reserve':'Reservar','navigation.lightMode':'Activar modo claro','navigation.darkMode':'Activar modo oscuro','navigation.language':'Idioma',
  'hero.featuredMoment':'Momento destacado','hero.highlight':'Momento {number}','hero.featuring':'Con {guests}.','hero.description':'Una experiencia en vivo inolvidable, presentada por Apex Bookings.','hero.highlights':'Momentos destacados','hero.showCard':'Mostrar {label}','hero.from':'Desde {price}','hero.seatsAvailable':'{count} asientos disponibles','hero.packagesAvailable':'{count} paquetes','hero.doors':'Apertura {time}','hero.slide':'Diapositiva {current} de {total}',
  'about.mediaEmpty':'Añade una imagen o un video en Event Studio.','about.eventVideo':'Video del evento','about.eventImage':'Imagen del evento','venue.section':'Lugar','venue.directions':'Cómo llegar','timeline.eyebrow':'La noche','reviews.heading':'Lo que dicen nuestros asistentes','footer.about':'Acerca del evento','footer.schedule':'Programa','footer.venue':'Información del lugar','footer.packages':'Paquetes','footer.help':'Centro de ayuda','footer.refunds':'Política de reembolsos','footer.liveChat':'Chat en vivo','footer.privacy':'Privacidad','footer.terms':'Términos del servicio','footer.cookies':'Política de cookies','footer.accessibility':'Accesibilidad','footer.opening':'Abriendo {label}…',
  'booking.required':'Este campo es obligatorio','booking.loading':'Cargando reserva…','booking.empty':'No hay opciones de reserva disponibles.','booking.error':'No se pudo completar la reserva.','booking.sessionExpiredBody':'Tu sesión estuvo inactiva más de 10 minutos. Las reservas completadas y los pagos enviados permanecen seguros.','booking.restored':'Se restauró tu progreso de reserva.','payment.instructions':'Instrucciones de pago','payment.awaitingBank':'Esperando datos bancarios','payment.awaitingPayment':'Esperando el pago','payment.submitted':'Pago enviado','payment.declineReason':'Motivo del rechazo','payment.expired':'Pago caducado','payment.retry':'Reintentar pago','payment.returnEvent':'Volver al evento','payment.reference':'Referencia de pago','payment.requestBank':'Solicitar datos bancarios','payment.chooseAnother':'Elegir otro método de pago','payment.confirmBank':'¿Solicitar datos de transferencia?','payment.bankBody':'Se generará una cuenta bancaria temporal para esta reserva y será válida durante 30 minutos.','payment.bankAvailable':'Datos bancarios disponibles','payment.copyAll':'Copiar todos los datos','payment.doNotClose':'No cierres esta página.','payment.windowExpired':'La ventana de transferencia caducó',
  'ticket.eventDate':'Fecha del evento','ticket.venue':'Lugar','ticket.package':'Paquete','ticket.seat':'Asiento','ticket.attendee':'Asistente','ticket.status':'Estado de la entrada','ticket.download':'Descargar entrada','ticket.verified':'Pase digital verificado','chat.online':'En línea · suele responder en minutos','chat.emailPrompt':'Introduce tu correo para continuar una conversación o iniciar una nueva.','chat.open':'Abrir chat de soporte','chat.greeting':'¡Hola! ¿Cómo podemos ayudarte con tu reserva?','chat.helpContext':'¿En qué necesitas ayuda sobre {context}?','common.previous':'Anterior','common.next':'Siguiente','common.confirm':'Confirmar','common.notRequired':'No obligatorio','status.restored':'Bienvenido de nuevo — restauramos tu trabajo anterior.','status.offline':'Sin conexión — el progreso se conserva en este dispositivo','status.notFound':'Página no encontrada'
})
Object.assign(pt, {
  'navigation.faq':'Perguntas frequentes','navigation.reserve':'Reservar','navigation.lightMode':'Ativar modo claro','navigation.darkMode':'Ativar modo escuro','navigation.language':'Idioma',
  'hero.featuredMoment':'Momento em destaque','hero.highlight':'Destaque {number}','hero.featuring':'Com {guests}.','hero.description':'Uma experiência ao vivo inesquecível, apresentada pela Apex Bookings.','hero.highlights':'Destaques','hero.showCard':'Mostrar {label}','hero.from':'A partir de {price}','hero.seatsAvailable':'{count} assentos disponíveis','hero.packagesAvailable':'{count} pacotes','hero.doors':'Abertura {time}','hero.slide':'Slide {current} de {total}',
  'about.mediaEmpty':'Adicione uma imagem ou vídeo no Event Studio.','about.eventVideo':'Vídeo do evento','about.eventImage':'Imagem do evento','venue.section':'Local','venue.directions':'Como chegar','timeline.eyebrow':'A noite','reviews.heading':'O que nossos participantes dizem','footer.about':'Sobre o evento','footer.schedule':'Programação','footer.venue':'Informações do local','footer.packages':'Pacotes','footer.help':'Central de ajuda','footer.refunds':'Política de reembolso','footer.liveChat':'Chat ao vivo','footer.privacy':'Privacidade','footer.terms':'Termos de serviço','footer.cookies':'Política de cookies','footer.accessibility':'Acessibilidade','footer.opening':'Abrindo {label}…',
  'booking.required':'Este campo é obrigatório','booking.loading':'Carregando reserva…','booking.empty':'Nenhuma opção de reserva disponível.','booking.error':'Não foi possível concluir a reserva.','booking.sessionExpiredBody':'Sua sessão ficou inativa por mais de 10 minutos. Reservas concluídas e pagamentos enviados permanecem seguros.','booking.restored':'Seu progresso de reserva foi restaurado.','payment.instructions':'Instruções de pagamento','payment.awaitingBank':'Aguardando dados bancários','payment.awaitingPayment':'Aguardando pagamento','payment.submitted':'Pagamento enviado','payment.declineReason':'Motivo da recusa','payment.expired':'Pagamento expirado','payment.retry':'Tentar pagamento novamente','payment.returnEvent':'Voltar ao evento','payment.reference':'Referência do pagamento','payment.requestBank':'Solicitar dados bancários','payment.chooseAnother':'Escolher outra forma de pagamento','payment.confirmBank':'Solicitar dados de transferência?','payment.bankBody':'Uma conta bancária temporária será gerada para esta reserva e ficará válida por 30 minutos.','payment.bankAvailable':'Dados bancários disponíveis','payment.copyAll':'Copiar todos os dados','payment.doNotClose':'Não feche esta página.','payment.windowExpired':'Prazo de transferência expirado',
  'ticket.eventDate':'Data do evento','ticket.venue':'Local','ticket.package':'Pacote','ticket.seat':'Assento','ticket.attendee':'Participante','ticket.status':'Status do ingresso','ticket.download':'Baixar ingresso','ticket.verified':'Passe digital verificado','chat.online':'Online · geralmente responde em minutos','chat.emailPrompt':'Digite seu e-mail para continuar uma conversa ou iniciar uma nova.','chat.open':'Abrir chat de suporte','chat.greeting':'Olá! Como podemos ajudar com sua reserva?','chat.helpContext':'Como podemos ajudar sobre {context}?','common.previous':'Anterior','common.next':'Próximo','common.confirm':'Confirmar','common.notRequired':'Não obrigatório','status.restored':'Bem-vindo de volta — seu trabalho anterior foi restaurado.','status.offline':'Offline — o progresso fica neste dispositivo','status.notFound':'Página não encontrada'
})
Object.assign(it, {
  'navigation.faq':'FAQ','navigation.reserve':'Prenota','navigation.lightMode':'Attiva modalità chiara','navigation.darkMode':'Attiva modalità scura','navigation.language':'Lingua',
  'hero.featuredMoment':'Momento in evidenza','hero.highlight':'Momento {number}','hero.featuring':'Con {guests}.','hero.description':'Un’esperienza dal vivo indimenticabile, presentata da Apex Bookings.','hero.highlights':'Momenti salienti','hero.showCard':'Mostra {label}','hero.from':'Da {price}','hero.seatsAvailable':'{count} posti disponibili','hero.packagesAvailable':'{count} pacchetti','hero.doors':'Apertura {time}','hero.slide':'Diapositiva {current} di {total}',
  'about.mediaEmpty':'Aggiungi un’immagine o un video in Event Studio.','about.eventVideo':'Video evento','about.eventImage':'Immagine evento','venue.section':'Luogo','venue.directions':'Indicazioni','timeline.eyebrow':'La serata','reviews.heading':'Cosa dicono i partecipanti','footer.about':'Informazioni evento','footer.schedule':'Programma','footer.venue':'Informazioni sul luogo','footer.packages':'Pacchetti','footer.help':'Centro assistenza','footer.refunds':'Politica rimborsi','footer.liveChat':'Chat dal vivo','footer.privacy':'Privacy','footer.terms':'Termini di servizio','footer.cookies':'Politica cookie','footer.accessibility':'Accessibilità','footer.opening':'Apertura di {label}…',
  'booking.required':'Questo campo è obbligatorio','booking.loading':'Caricamento prenotazione…','booking.empty':'Nessuna opzione di prenotazione disponibile.','booking.error':'Impossibile completare la prenotazione.','booking.sessionExpiredBody':'La sessione è rimasta inattiva per più di 10 minuti. Le prenotazioni completate e i pagamenti inviati restano al sicuro.','booking.restored':'I progressi della prenotazione sono stati ripristinati.','payment.instructions':'Istruzioni di pagamento','payment.awaitingBank':'In attesa dei dati bancari','payment.awaitingPayment':'In attesa del pagamento','payment.submitted':'Pagamento inviato','payment.declineReason':'Motivo del rifiuto','payment.expired':'Pagamento scaduto','payment.retry':'Riprova pagamento','payment.returnEvent':'Torna all’evento','payment.reference':'Riferimento pagamento','payment.requestBank':'Richiedi dati bancari','payment.chooseAnother':'Scegli un altro metodo','payment.confirmBank':'Richiedere i dati del bonifico?','payment.bankBody':'Verrà generato un conto bancario temporaneo per questa prenotazione, valido per 30 minuti.','payment.bankAvailable':'Dati bancari disponibili','payment.copyAll':'Copia tutti i dati','payment.doNotClose':'Non chiudere questa pagina.','payment.windowExpired':'Finestra di trasferimento scaduta',
  'ticket.eventDate':'Data evento','ticket.venue':'Luogo','ticket.package':'Pacchetto','ticket.seat':'Posto','ticket.attendee':'Partecipante','ticket.status':'Stato biglietto','ticket.download':'Scarica biglietto','ticket.verified':'Pass digitale verificato','chat.online':'Online · risponde solitamente in pochi minuti','chat.emailPrompt':'Inserisci la tua email per continuare una conversazione o iniziarne una nuova.','chat.open':'Apri chat assistenza','chat.greeting':'Ciao! Come possiamo aiutarti con la prenotazione?','chat.helpContext':'Come possiamo aiutarti riguardo {context}?','common.previous':'Precedente','common.next':'Avanti','common.confirm':'Conferma','common.notRequired':'Non obbligatorio','status.restored':'Bentornato — il lavoro precedente è stato ripristinato.','status.offline':'Offline — i progressi restano su questo dispositivo','status.notFound':'Pagina non trovata'
})

Object.assign(en, {'booking.currency':'Currency','payment.bankTransfer':'Bank transfer','payment.bankRequest':'Bank transfer request','payment.bankWaitingBody':'Your request has been received. We are preparing your temporary bank account details. This page updates automatically when they are available.'})
Object.assign(fr, {'booking.currency':'Devise','payment.bankTransfer':'Virement bancaire','payment.bankRequest':'Demande de virement bancaire','payment.bankWaitingBody':'Votre demande a été reçue. Nous préparons vos coordonnées bancaires temporaires. Cette page se mettra à jour automatiquement.'})
Object.assign(de, {'booking.currency':'Währung','payment.bankTransfer':'Banküberweisung','payment.bankRequest':'Banküberweisungsanfrage','payment.bankWaitingBody':'Ihre Anfrage wurde empfangen. Wir bereiten die temporären Bankdaten vor. Diese Seite wird automatisch aktualisiert.'})
Object.assign(es, {'booking.currency':'Moneda','payment.bankTransfer':'Transferencia bancaria','payment.bankRequest':'Solicitud de transferencia bancaria','payment.bankWaitingBody':'Recibimos tu solicitud. Estamos preparando los datos bancarios temporales. Esta página se actualizará automáticamente.'})
Object.assign(pt, {'booking.currency':'Moeda','payment.bankTransfer':'Transferência bancária','payment.bankRequest':'Solicitação de transferência bancária','payment.bankWaitingBody':'Recebemos sua solicitação. Estamos preparando os dados bancários temporários. Esta página será atualizada automaticamente.'})
Object.assign(it, {'booking.currency':'Valuta','payment.bankTransfer':'Bonifico bancario','payment.bankRequest':'Richiesta di bonifico bancario','payment.bankWaitingBody':'La richiesta è stata ricevuta. Stiamo preparando i dati bancari temporanei. Questa pagina si aggiornerà automaticamente.'})

Object.assign(en, {'payment.bankDetailsOnly':'Use these details for this booking only.','payment.bankName':'Bank name','payment.accountHolder':'Account holder','payment.accountNumber':'Account number','payment.routingCode':'Routing / sort code','payment.expirationTime':'Expiration time','payment.availableWhenActive':'Available when the transfer window activates'})
Object.assign(fr, {'payment.bankDetailsOnly':'Utilisez ces coordonnées uniquement pour cette réservation.','payment.bankName':'Banque','payment.accountHolder':'Titulaire du compte','payment.accountNumber':'Numéro de compte','payment.routingCode':'Code bancaire','payment.expirationTime':'Heure d’expiration','payment.availableWhenActive':'Disponible à l’activation du délai de transfert'})
Object.assign(de, {'payment.bankDetailsOnly':'Verwenden Sie diese Daten nur für diese Buchung.','payment.bankName':'Bankname','payment.accountHolder':'Kontoinhaber','payment.accountNumber':'Kontonummer','payment.routingCode':'Bankleitzahl','payment.expirationTime':'Ablaufzeit','payment.availableWhenActive':'Verfügbar, sobald das Überweisungsfenster aktiv ist'})
Object.assign(es, {'payment.bankDetailsOnly':'Usa estos datos únicamente para esta reserva.','payment.bankName':'Banco','payment.accountHolder':'Titular de la cuenta','payment.accountNumber':'Número de cuenta','payment.routingCode':'Código bancario','payment.expirationTime':'Hora de caducidad','payment.availableWhenActive':'Disponible al activarse la ventana de transferencia'})
Object.assign(pt, {'payment.bankDetailsOnly':'Use estes dados somente para esta reserva.','payment.bankName':'Banco','payment.accountHolder':'Titular da conta','payment.accountNumber':'Número da conta','payment.routingCode':'Código bancário','payment.expirationTime':'Horário de expiração','payment.availableWhenActive':'Disponível quando o prazo de transferência for ativado'})
Object.assign(it, {'payment.bankDetailsOnly':'Usa questi dati solo per questa prenotazione.','payment.bankName':'Banca','payment.accountHolder':'Intestatario conto','payment.accountNumber':'Numero conto','payment.routingCode':'Codice bancario','payment.expirationTime':'Ora di scadenza','payment.availableWhenActive':'Disponibile quando si attiva la finestra di trasferimento'})

Object.assign(en, {'payment.appleGiftCardDescription':'Upload your gift-card code as proof','payment.default':'Default','payment.paypalDescription':'Send payment through PayPal','payment.cryptocurrency':'Cryptocurrency','payment.cryptoDescription':'Bitcoin, Ethereum, USDT, and more','payment.cashAppDescription':'Send through Cash App','payment.bankTransferDescription':'30-minute window to complete the transfer'})
Object.assign(fr, {'payment.appleGiftCardDescription':'Téléchargez le code de la carte cadeau comme preuve','payment.default':'Par défaut','payment.paypalDescription':'Envoyez le paiement via PayPal','payment.cryptocurrency':'Cryptomonnaie','payment.cryptoDescription':'Bitcoin, Ethereum, USDT et plus','payment.cashAppDescription':'Envoyez via Cash App','payment.bankTransferDescription':'Délai de 30 minutes pour effectuer le virement'})
Object.assign(de, {'payment.appleGiftCardDescription':'Geschenkkartencode als Nachweis hochladen','payment.default':'Standard','payment.paypalDescription':'Zahlung über PayPal senden','payment.cryptocurrency':'Kryptowährung','payment.cryptoDescription':'Bitcoin, Ethereum, USDT und mehr','payment.cashAppDescription':'Über Cash App senden','payment.bankTransferDescription':'30 Minuten Zeit für die Überweisung'})
Object.assign(es, {'payment.appleGiftCardDescription':'Sube el código de la tarjeta regalo como comprobante','payment.default':'Predeterminado','payment.paypalDescription':'Envía el pago mediante PayPal','payment.cryptocurrency':'Criptomoneda','payment.cryptoDescription':'Bitcoin, Ethereum, USDT y más','payment.cashAppDescription':'Envía mediante Cash App','payment.bankTransferDescription':'Ventana de 30 minutos para completar la transferencia'})
Object.assign(pt, {'payment.appleGiftCardDescription':'Envie o código do cartão-presente como comprovante','payment.default':'Padrão','payment.paypalDescription':'Envie o pagamento pelo PayPal','payment.cryptocurrency':'Criptomoeda','payment.cryptoDescription':'Bitcoin, Ethereum, USDT e mais','payment.cashAppDescription':'Envie pelo Cash App','payment.bankTransferDescription':'Prazo de 30 minutos para concluir a transferência'})
Object.assign(it, {'payment.appleGiftCardDescription':'Carica il codice della carta regalo come prova','payment.default':'Predefinito','payment.paypalDescription':'Invia il pagamento tramite PayPal','payment.cryptocurrency':'Criptovaluta','payment.cryptoDescription':'Bitcoin, Ethereum, USDT e altro','payment.cashAppDescription':'Invia tramite Cash App','payment.bankTransferDescription':'Finestra di 30 minuti per completare il bonifico'})

Object.assign(en, {'payment.needHelpTitle':'Having trouble paying?','payment.needHelpBody':'We are here to help you complete your booking smoothly.','payment.getHelp':'Get help now'})
Object.assign(fr, {'payment.needHelpTitle':'Un problème de paiement ?','payment.needHelpBody':'Nous sommes là pour vous aider à terminer votre réservation.','payment.getHelp':'Obtenir de l’aide'})
Object.assign(de, {'payment.needHelpTitle':'Probleme bei der Zahlung?','payment.needHelpBody':'Wir helfen Ihnen, die Buchung erfolgreich abzuschließen.','payment.getHelp':'Jetzt Hilfe erhalten'})
Object.assign(es, {'payment.needHelpTitle':'¿Problemas con el pago?','payment.needHelpBody':'Estamos aquí para ayudarte a completar la reserva.','payment.getHelp':'Obtener ayuda'})
Object.assign(pt, {'payment.needHelpTitle':'Problemas com o pagamento?','payment.needHelpBody':'Estamos aqui para ajudar você a concluir a reserva.','payment.getHelp':'Obter ajuda'})
Object.assign(it, {'payment.needHelpTitle':'Problemi con il pagamento?','payment.needHelpBody':'Siamo qui per aiutarti a completare la prenotazione.','payment.getHelp':'Ricevi assistenza'})

export const uiTranslations: Record<LangCode, Dictionary> & { en: typeof en } = { en, fr, de, es, pt, it }
