import { createContext, useContext, useEffect, useMemo, useState, type PropsWithChildren } from 'react'
import type { Session } from '@supabase/supabase-js'
import { supabase } from '../../lib/supabase'

type AuthContextValue = { session: Session | null; demoAdmin: boolean; loading: boolean; signIn: (email: string, password: string, remember: boolean) => Promise<string | null>; resetPassword: (email: string) => Promise<string | null>; enableDemoAdmin: () => void; signOut: () => Promise<void> }
const AuthContext = createContext<AuthContextValue | undefined>(undefined)
const demoKey = 'apex.demo-admin'
export function AuthProvider({ children }: PropsWithChildren) { const [session, setSession] = useState<Session | null>(null); const [demoAdmin, setDemoAdmin] = useState(() => !supabase && localStorage.getItem(demoKey) === 'true'); const [loading, setLoading] = useState(true); useEffect(() => { if (!supabase) { setLoading(false); return }; void supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false) }); const { data: listener } = supabase.auth.onAuthStateChange((_event, nextSession) => setSession(nextSession)); return () => listener.subscription.unsubscribe() }, []); const value = useMemo<AuthContextValue>(() => ({ session, demoAdmin, loading, signIn: async (email, password, _remember) => { if (!supabase) return 'Supabase is not configured. Use development access below.'; const { error } = await supabase.auth.signInWithPassword({ email, password }); return error?.message ?? null }, resetPassword: async email => { if (!supabase) return 'Supabase is not configured.'; const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/admin/login` }); return error?.message ?? null }, enableDemoAdmin: () => { localStorage.setItem(demoKey, 'true'); setDemoAdmin(true) }, signOut: async () => { if (supabase) await supabase.auth.signOut(); localStorage.removeItem(demoKey); setDemoAdmin(false); setSession(null) } }), [demoAdmin, loading, session]); return <AuthContext.Provider value={value}>{children}</AuthContext.Provider> }
export function useAuth() { const context = useContext(AuthContext); if (!context) throw new Error('useAuth must be used within AuthProvider'); return context }
