import { useMemo, useState } from 'react'
import { adminEventStore, type ManagedEvent } from '../events/adminEventStore'
import { analyticsStore } from './analyticsStore'
import { paymentReviewStore } from '../payments/paymentReviewStore'

const card = (label: string, value: string | number, accent = '#00FF88') => <div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><div className="text-2xl font-serif font-bold" style={{ color: accent }}>{value}</div><div className="mt-1 text-[10px] font-mono uppercase tracking-wider text-zinc-500">{label}</div></div>
export function AnalyticsDashboard() {
  const events = adminEventStore.list().filter(event => event.status !== 'archived')
  const [eventId, setEventId] = useState('all')
  const selected = eventId === 'all' ? events : events.filter(event => event.id === eventId)
  const stats = useMemo(() => { const payments = paymentReviewStore.list().filter(payment => selected.some(event => event.id === payment.eventId)); const metrics = selected.map(event => analyticsStore.get(event.id)); const seats = selected.flatMap(event => event.seats ?? []); const sold = seats.filter(seat => seat.status === 'sold').length; const reserved = seats.filter(seat => seat.status === 'reserved').length; const capacity = selected.reduce((sum, event) => sum + event.capacity, 0); const approved = payments.filter(payment => payment.status === 'approved'); return { views: metrics.reduce((sum, metric) => sum + metric.views, 0), visitors: metrics.reduce((sum, metric) => sum + metric.uniqueVisitors.length, 0), sold, reserved, capacity, revenue: approved.reduce((sum, payment) => sum + payment.amount, 0), pending: payments.filter(payment => payment.status === 'pending').length, approved: approved.length, rejected: payments.filter(payment => payment.status === 'rejected').length, cta: metrics.reduce((sum, metric) => sum + metric.ctaClicks, 0), packageClicks: metrics.reduce((sum, metric) => sum + metric.packageClicks, 0) } }, [selected])
  const exportCsv = () => { const rows = [['Metric','Value'],['Event views',String(stats.views)],['Unique visitors',String(stats.visitors)],['Tickets sold',String(stats.sold)],['Remaining seats',String(Math.max(0, stats.capacity - stats.sold - stats.reserved))],['Gross revenue',String(stats.revenue)],['Pending payments',String(stats.pending)],['Approved payments',String(stats.approved)],['Rejected payments',String(stats.rejected)]]; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([rows.map(row => row.join(',')).join('\n')], { type: 'text/csv' })); link.download = 'apex-event-report.csv'; link.click(); URL.revokeObjectURL(link.href) }
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-mono uppercase tracking-widest text-emerald-400">Automatic analytics</p><h1 className="font-serif text-2xl font-bold text-white">Event performance</h1></div><div className="flex gap-2"><select value={eventId} onChange={event => setEventId(event.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs text-white"><option value="all">All events</option>{events.map(event => <option key={event.id} value={event.id}>{event.title}</option>)}</select><button onClick={exportCsv} className="rounded-xl bg-white/5 px-3 py-2 text-xs text-zinc-200">Export CSV</button></div></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{card('Event views', stats.views, '#22D3EE')}{card('Unique visitors', stats.visitors)}{card('Tickets sold', stats.sold, '#8B5CF6')}{card('Remaining seats', Math.max(0, stats.capacity - stats.sold - stats.reserved), '#F59E0B')}{card('Gross revenue', `$${stats.revenue.toLocaleString()}`, '#00FF88')}{card('Pending payments', stats.pending, '#F59E0B')}{card('Approved payments', stats.approved)}{card('Rejected payments', stats.rejected, '#EF4444')}{card('Conversion rate', stats.views ? `${((stats.sold / stats.views) * 100).toFixed(1)}%` : '0%')}{card('Package clicks', stats.packageClicks, '#8B5CF6')}</div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="text-xs font-mono uppercase tracking-wider text-zinc-500">Seat occupancy</div><div className="mt-4 h-3 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${stats.capacity ? ((stats.sold + stats.reserved) / stats.capacity) * 100 : 0}%` }}/></div><div className="mt-3 flex justify-between text-xs text-zinc-400"><span>{stats.sold} sold · {stats.reserved} reserved</span><span>{stats.capacity ? Math.round(((stats.sold + stats.reserved) / stats.capacity) * 100) : 0}% occupied</span></div></div><div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="text-xs font-mono uppercase tracking-wider text-zinc-500">Engagement</div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-white/5 p-3"><span className="text-zinc-500">CTA clicks</span><strong className="mt-1 block text-lg text-white">{stats.cta}</strong></div><div className="rounded-xl bg-white/5 p-3"><span className="text-zinc-500">Package clicks</span><strong className="mt-1 block text-lg text-white">{stats.packageClicks}</strong></div></div></div></div></div>
}
