import { useMemo, useState } from 'react'

type Guide = { area: string; title: string; summary: string; steps: string[]; tags: string[] }

const guides: Guide[] = [
  { area: 'Getting started', title: 'Admin dashboard overview', summary: 'Use the dashboard as the live command centre for activity recorded by the booking, payment, and support modules.', steps: ['Review approved revenue and booking approval rate.', 'Open a country row to inspect the related customer activity.', 'Use the sidebar to move into the operational modules.'], tags: ['overview', 'analytics', 'dashboard'] },
  { area: 'Events', title: 'Create, edit, duplicate, and publish an event page', summary: 'Every event begins from the booking template and remains a draft until it is published.', steps: ['Open Event and select Create Event.', 'Enter event details, packages, seats, and payment methods.', 'Continue to the booking-page editor to update sections and media.', 'Publish when the details are ready; use Duplicate to clone an existing event.'], tags: ['event', 'create', 'duplicate', 'publish', 'page'] },
  { area: 'Events', title: 'Edit the default booking template', summary: 'The default template is the starting point for new event pages.', steps: ['Open Event, then select Edit Template.', 'Click a page section to select it and double-click text or images to change them.', 'Save the template before creating the next event.', 'Use Preview to inspect the public mobile and desktop experience.'], tags: ['template', 'editor', 'default', 'page'] },
  { area: 'Bookings', title: 'Manage bookings and customers', summary: 'Bookings are created from public checkout and appear here with their payment state.', steps: ['Filter by status or search a customer, event, or reference.', 'Open a booking to review package, seat, and payment details.', 'Use the customer information to investigate activity before taking payment action.'], tags: ['booking', 'customer', 'seat', 'ticket'] },
  { area: 'Payments', title: 'Review payments and bank transfers', summary: 'Payment proofs and transfer requests enter the Payment Center for manual review.', steps: ['Open the proof and check the booking reference, seat, and amount.', 'Approve to generate the approved payment workflow and customer email queue.', 'Reject only after adding a clear decline reason.', 'For bank transfers, enter real account details and send the 30-minute payment window.'], tags: ['payment', 'crypto', 'bank', 'proof', 'approval'] },
  { area: 'Settings', title: 'Configure payments, crypto, branding, media, and notifications', summary: 'Settings are shared configuration for public booking pages.', steps: ['Use Branding and Media to control visual assets.', 'Enable payment methods and add cryptocurrency wallets before publishing an event.', 'Use Social Proof to control purchase-popup visibility and mode.', 'Review email, language, currency, support, and notification preferences before launch.'], tags: ['settings', 'branding', 'media', 'crypto', 'social proof', 'notifications'] },
  { area: 'Support', title: 'Use public and admin support chat', summary: 'Visitors enter an email address before a conversation is opened; returning visitors reuse their saved conversation.', steps: ['Open Live Chat to review unread conversations.', 'Reply with text or supported attachments.', 'Use customer and booking details to resolve the request.', 'Customer replies and admin responses are retained against the conversation.'], tags: ['chat', 'support', 'email', 'media'] },
  { area: 'Email and security', title: 'Understand email delivery and protected access', summary: 'Admin routes require Supabase authentication. Customer email events are queued for the configured delivery service.', steps: ['Configure Gmail SMTP secrets in the deployment environment.', 'Check payment approval, decline, proof, and support-reply email queue activity.', 'Never use a service-role key in the browser.', 'Use the five-tap logo gesture only on a booking page to reach the secure admin sign-in page.'], tags: ['email', 'smtp', 'security', 'authentication'] },
]

export function DocumentationPage() {
  const [query, setQuery] = useState('')
  const [area, setArea] = useState('All')
  const areas = ['All', ...Array.from(new Set(guides.map(guide => guide.area)))]
  const visible = useMemo(() => guides.filter(guide => {
    const matchesArea = area === 'All' || guide.area === area
    const text = `${guide.title} ${guide.summary} ${guide.steps.join(' ')} ${guide.tags.join(' ')}`.toLowerCase()
    return matchesArea && text.includes(query.trim().toLowerCase())
  }), [area, query])

  return <div className="mx-auto max-w-5xl space-y-6"><div className="rounded-3xl border border-emerald-400/20 bg-gradient-to-br from-emerald-400/10 via-white/[.03] to-violet-500/10 p-6"><p className="font-mono text-[10px] uppercase tracking-[.22em] text-emerald-300">Apex Bookings handbook</p><h1 className="mt-2 font-serif text-3xl font-bold text-white">Everything your team needs to operate the app.</h1><p className="mt-3 max-w-3xl text-sm leading-relaxed text-zinc-300">Search a feature, filter by area, or use the onboarding toggle at the bottom of every admin page for contextual guidance.</p><div className="mt-5 flex flex-col gap-3 sm:flex-row"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search events, payments, email, chat, settings…" className="min-w-0 flex-1 rounded-xl border border-white/15 bg-black/25 px-4 py-3 text-sm text-white outline-none placeholder:text-zinc-500 focus:border-emerald-400"/><select value={area} onChange={event => setArea(event.target.value)} className="rounded-xl border border-white/15 bg-zinc-950 px-4 py-3 text-sm text-white outline-none">{areas.map(option => <option key={option}>{option}</option>)}</select></div></div><div className="flex flex-wrap gap-2">{areas.map(option => <button key={option} onClick={() => setArea(option)} className={`rounded-full px-3 py-1.5 text-xs ${area === option ? 'bg-emerald-400 font-semibold text-zinc-950' : 'bg-white/5 text-zinc-300'}`}>{option}</button>)}</div><div className="grid gap-4 md:grid-cols-2">{visible.map(guide => <article key={guide.title} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-[10px] font-mono uppercase tracking-widest text-emerald-300">{guide.area}</p><h2 className="mt-2 font-serif text-xl font-bold text-white">{guide.title}</h2><p className="mt-2 text-sm leading-relaxed text-zinc-400">{guide.summary}</p><ol className="mt-4 space-y-2 text-sm text-zinc-200">{guide.steps.map((step, index) => <li key={step} className="flex gap-3"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-emerald-400/15 text-[10px] font-bold text-emerald-300">{index + 1}</span><span>{step}</span></li>)}</ol></article>)}</div>{!visible.length && <div className="rounded-2xl border border-dashed border-white/15 p-12 text-center text-sm text-zinc-400">No guide matches that search. Try a broader term.</div>}</div>
}
