create extension if not exists "pgcrypto";

do $$ begin create type public.event_status as enum ('draft','scheduled','live','sold_out','completed','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.seat_status as enum ('available','reserved','sold','disabled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_method as enum ('apple_gift_card','paypal','bitcoin','cash_app','bank_transfer'); exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_status as enum ('pending','approved','rejected','expired'); exception when duplicate_object then null; end $$;

create table if not exists public.organizations (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table if not exists public.customers (id uuid primary key default gen_random_uuid(), full_name text not null, email text not null unique, phone text, created_at timestamptz not null default now());
create table if not exists public.events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), slug text not null unique, name text not null, venue text, address text, google_map_address text, starts_at timestamptz not null, status public.event_status not null default 'draft', banner_path text, event_facts text, important_information text, created_at timestamptz not null default now());
create table if not exists public.packages (id uuid primary key default gen_random_uuid(), event_id uuid not null references public.events(id) on delete cascade, name text not null, price numeric(12,2) not null check (price >= 0), offer text, capacity integer not null check (capacity >= 0));
create table if not exists public.seats (id uuid primary key default gen_random_uuid(), event_id uuid not null references public.events(id) on delete cascade, package_id uuid references public.packages(id) on delete set null, label text not null, status public.seat_status not null default 'available', unique(event_id, label));
create table if not exists public.bookings (id uuid primary key default gen_random_uuid(), reference text not null unique, event_id uuid not null references public.events(id), customer_id uuid not null references public.customers(id), seat_id uuid references public.seats(id), package_id uuid references public.packages(id), status text not null default 'pending', created_at timestamptz not null default now());
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), booking_id uuid not null references public.bookings(id) on delete cascade, method public.payment_method not null, status public.payment_status not null default 'pending', amount numeric(12,2) not null check (amount >= 0), expires_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.media (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), bucket text not null check (bucket in ('payment-proofs','event-images','ticket-assets','chat-files')), path text not null, mime_type text, size_bytes bigint, created_at timestamptz not null default now(), unique(bucket,path));
create table if not exists public.payment_proofs (id uuid primary key default gen_random_uuid(), payment_id uuid not null references public.payments(id) on delete cascade, media_id uuid not null references public.media(id) on delete cascade, created_at timestamptz not null default now(), unique(payment_id, media_id));
create table if not exists public.messages (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id), booking_id uuid references public.bookings(id), body text, media_id uuid references public.media(id), read_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), type text not null, payload jsonb not null default '{}'::jsonb, read_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.settings (organization_id uuid primary key references public.organizations(id) on delete cascade, payment_methods public.payment_method[] not null default array['apple_gift_card','paypal','bitcoin','cash_app','bank_transfer']::public.payment_method[], ticket_template jsonb not null default '{}'::jsonb, email_template jsonb not null default '{}'::jsonb, chat_settings jsonb not null default '{}'::jsonb);

create index if not exists bookings_event_id_idx on public.bookings(event_id); create index if not exists payments_booking_id_idx on public.payments(booking_id); create index if not exists seats_event_id_status_idx on public.seats(event_id,status); create index if not exists messages_customer_id_created_at_idx on public.messages(customer_id,created_at desc);
